# Generated by Django 4.0.2 on 2022-02-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerywebsite', '0002_customer_city_customer_pin_code_customer_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='p_id',
            field=models.IntegerField(default=0),
        ),
    ]
