# Generated by Django 4.0.2 on 2022-03-08 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerywebsite', '0003_cart_p_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='payment_id',
            field=models.CharField(default='', max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_mode',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='tracking_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerywebsite.orderplaced')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerywebsite.product')),
            ],
        ),
    ]
