# Generated by Django 4.0.2 on 2022-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerywebsite', '0004_orderplaced_payment_id_orderplaced_payment_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
