# Generated by Django 4.0.2 on 2022-03-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerywebsite', '0005_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='total_price',
            field=models.IntegerField(default=1),
        ),
    ]
