# Generated by Django 4.0.2 on 2022-03-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerywebsite', '0007_remove_orderplaced_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
